import Head from 'next/head'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import styles from '@/styles/layout.module.css'

const inter = Inter({ subsets: ['latin'], weight: ['300'] })

export default function Layout({ title, children, className, googleAnalyticsId }) {
  return (
    <>
      <Script strategy="lazyOnload" src={'https://www.googletagmanager.com/gtag/js?id=' + googleAnalyticsId} />
      <Script id="google-analytics" strategy="lazyOnload">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${googleAnalyticsId}', {page_path: window.location.pathname});
        `}
      </Script>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {children}
      </main>
    </>
  )
}
