import Head from "next/head";
import { Lato } from "next/font/google";
import styles from "@/styles/layout.module.css";

const lato = Lato({ subsets: ["latin"], weight: ['400'] });

export default function Layout({ title, children, className }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${lato.className}`}>
        {children}
      </main>
    </>
  )
}